blueprint:
  name: Turn Light ON and OFF
  description: Turn light on when motion is detected and off when motion is not detected after a number of minutes.
  domain: automation
  input:
    motion_sensor:
      name: Motion Sensor
      description: Choose the Hue motion sensor to control the lights.
      selector:
        entity:
          domain: binary_sensor
          device_class: occupancy
    target_light:
      name: Target Light
      description: Choose the lights that you want to control.
      selector:
        target:
          entity:
            domain: light
    delay_time:
      name: Number of mintes 
      description: Number of minutes, afterwhich the lights will turn off.
      selector:
        number:
          min: 0
          max: 10
          step: 1
          unit_of_measurement: "minutes"

trigger:
  - platform: state
    entity_id: !input motion_sensor

condition: []

action:
  - choose:
    - conditions:
      - condition: state
        entity_id: !input motion_sensor
        state: 'off'
        for:
          hours: 0
          minutes: 0
          seconds: 0
      sequence:
      - delay:
          hours: 0
          minutes: !input delay_time
          seconds: 0
          milliseconds: 0
      - service: light.turn_off
        data:
          transition: 10
        target: !input target_light
    - conditions:
      - condition: state
        entity_id: !input motion_sensor
        state: 'on'
      sequence:
      - service: light.turn_on
        data: {}
        target: !input target_light
    default: []
mode: restart